"""Add kosync_documents table

Revision ID: 43be53e3830a
Revises: e7b8c9d0a1b2
Create Date: 2026-01-21 07:27:19.245321

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43be53e3830a'
down_revision: str | Sequence[str] | None = 'e7b8c9d0a1b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if table exists to avoid errors on "dirty" databases
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'kosync_documents' not in tables:
        op.create_table('kosync_documents',
            sa.Column('document_hash', sa.String(length=32), nullable=False),
            sa.Column('progress', sa.String(length=512), nullable=True),
            sa.Column('percentage', sa.Float(), nullable=True),
            sa.Column('device', sa.String(length=128), nullable=True),
            sa.Column('device_id', sa.String(length=64), nullable=True),
            sa.Column('timestamp', sa.DateTime(), nullable=True),
            sa.Column('linked_abs_id', sa.String(length=255), nullable=True),
            sa.Column('first_seen', sa.DateTime(), nullable=True),
            sa.Column('last_updated', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('document_hash')
        )
        op.create_index(op.f('ix_kosync_documents_linked_abs_id'), 'kosync_documents', ['linked_abs_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kosync_documents_linked_abs_id'), table_name='kosync_documents')
    op.drop_table('kosync_documents')
    # ### end Alembic commands ###
